### ISSUE TITLE
vip balance see

### ISSUE THREAD

**Issue by CheAle14** [CheAle14/casino-bot#1]
12:24:12.101   [Error] Command: Discord.Commands.CommandException: Error occurred executing "balance see" for Anu$han#8233 in Four Aces Casino/about. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Casino.VIPBalance.ToEmbed() in D:\Documents\_CasinoDocs\CasinoBotRepo\src\CasinoClasses.cs:line 2518
   at DiscordBot.Modules.VIPModule.<SeeBalance>d__1.MoveNext() in D:\Documents\_CasinoDocs\CasinoBotRepo\src\Modules\VIPModule.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Commands.CommandInfo.<ExecuteAsyncInternalAsync>d__42.MoveNext()

**Comment by CheAle14** [comment]
Fixed in version 25.11.14
[Commit on bitbucket](https://bitbucket.org/cheale14/casino-bot/commits/4ef3c83bde910ea1d7a43269b3b700a2a85cc139)
